### PR TITLE
gdk4-wayland: generate bindings

### LINKED ISSUE #37: Generate gdk4-x11 & gdk4-wayland
Requires adding the proper gir files to gir-files first 
- [x] gdk4-x11
- [ ] gdk4-wayland

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
It's uses wayland-client from wayland-rs project. This requires some changes to the gir file as it's currently exposes c_types that are not exposed by the wayland-rs sys crate neither. 

Closes #37

### CODE REVIEW

**Review by sdroege — APPROVED** [review]
Looks good to me, do you have some use-case/example usage for this that you could put into examples4? :)

**Comment by bilelmoussaoui** [comment]
I have managed to get a very example working properly that allows you to get a window handle under wayland 
```rust
extern crate gio;
extern crate gtk;

use gio::prelude::*;
use gtk::prelude::*;

use std::env::args;

fn build_ui(application: &gtk::Application) {
    let window = gtk::ApplicationWindow::new(application);

    window.set_title("First GTK+ Program");
    window.set_default_size(350, 70);

    let button = gtk::ButtonBuilder::default()
        .label("Click me!")
        .margin_bottom(10)
        .margin_start(10)
        .margin_end(10)
        .margin_top(10)
        .build();
    let weak_win = window.clone();
    button.connect_clicked(move |btn| {
        let top_level = weak_win.get_surface().unwrap().downcast::<gdk_wayland::WaylandToplevel>().unwrap();

        top_level.export_handle(move |level, handle| {
            println!("{:#?}", handle);
        });
    });

    window.set_child(Some(&button));
    window.show();
}

fn main() {
    let application =
        gtk::Application::new(Some("com.github.gtk-rs.examples.basic"), Default::default())
            .expect("Initialization failed...");
    application.connect_activate(|app| {
        build_ui(app);
    });

    application.run(&args().collect::<Vec<_>>());
}
```
Though, the examples4 repo wasn't migrated yet, I'm planning to redo that from scratch as part of #36

**Comment by sdroege** [comment]
And what would you do with that window handle? :)

**Comment by bilelmoussaoui** [comment]
Call a fdo portal to take a screenshot and then display it on a gtk photo

**Comment by sdroege** [comment]
Ah I guess that makes sense

**Comment by bilelmoussaoui** [comment]
Per my very basic tests, it seems to work fine

**Pull request merged**
