### PR TITLE
Update actions

### PR DESCRIPTION
**Pull request by brianbarnatt7**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
@GuillaumeGomez @sdroege can you ban this one please?

**Comment by sdroege** [comment]
Done and also reported. Probably useless because it's easy enough to create new github users automatically :man_shrugging:
This really has to be fixed by github directly.

**Comment by bilelmoussaoui** [comment]
Indeed. For now that's all we can do anyway

**Comment by LegendaryGeek** [comment]
how does someone ban another user from a repositiory? the bot came to mine and his workflow ran 4 times...

**Comment by sdroege** [comment]
You click on the "three horizontal dots" button on the user's comment in your repo (next to the "reaction" button), and then you can block the user in your organization (or all repos of your user).

**Comment by LegendaryGeek** [comment]
thank you very much

**Pull request closed without merging**
