### PR TITLE
gdk: Cursor is Send

### PR DESCRIPTION
**Pull request by elmarco**
It only has read-only methods.

### CODE REVIEW

**Comment by sdroege** [comment]
I think that's wrong. The cursor can have a reference to a texture, which might be backed by OS resources (e.g. GL, Windows HWND, etc) and that's clearly not `Send`.

**Comment by elmarco** [comment]
Hmm.

https://docs.gtk.org/gdk4/class.Cursor.html#description

Cursors are immutable objects, so once you created them, there is no way to modify them later. You should create a new cursor when you want to change something about it.

Same for GdkTexture actually.

**Comment by sdroege** [comment]
Yes but you can't access textures from any other thread than the main thread (with the exception of memory textures).

**Comment by elmarco** [comment]
hmm ok

**Comment by sdroege** [comment]
That's generally the rule for anything in GDK that works with system resources.

**Pull request closed without merging**
