### PR TITLE
gtk: Remove outdated Gir.toml downstream fixes

### PR DESCRIPTION
**Pull request by sophie-h**
Not all of the annotations from PR #83 got accepted upstream.

- Rejected upstream MR https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/2887
- Accepted upstream changes https://gitlab.gnome.org/GNOME/gtk/-/commit/4434889e41e8acd81c4f5a83c631b7ca5c088234

Cc @bilelmoussaoui

### CODE REVIEW

**Comment by sophie-h** [comment]
There is a strange conflict with `TextView::get_extra_menu`. It's marked nullable in gtk4-rs, but nullable was [removed upstream](https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/2887/diffs#ed0c7fddf3902ef3570a462d9ee7cadfb2566879_9705_9705).

**Comment by sophie-h** [comment]
@bilelmoussaoui any idea what to do with the remaining "remove after https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/2887" annotations? Trust upstream?

**Comment by bilelmoussaoui** [comment]
> @bilelmoussaoui any idea what to do with the remaining "remove after https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/2887" annotations? Trust upstream?

I don't think upstream revisited all of those, but we should definitely remove the ones that aren't needed anymore

**Comment by sophie-h** [comment]
Imo this can be merged as is. I am revisiting the remaining annotations in others MRs (see #178 for example.)

**Comment by bilelmoussaoui** [comment]
> Imo this can be merged as is. I am revisiting the remaining annotations in others MRs (see #178 for example.)

It needs rebasing first :)

**Comment by sophie-h** [comment]
> It needs rebasing first :)

Oh, great, I force pushed my rebase away. Now it's back.

**Pull request merged**
