### PR TITLE
subclass/widget: Rework the default measure() vfunc

### PR DESCRIPTION
**Pull request by BrainBlasted**
The way we previously handled measure didn't work
with the way measure actually works. It caused
a critical issue as widget subclasses were using
a measure func that did not behave properly.

This would lead to a crash.

With these changes we now handle measure in a simple
"default" way.

### CODE REVIEW

**Review by sdroege — APPROVED** [review]
Seems fine to me but needs some checking if it's guaranteed that all callers initialize the 4 values

**Comment by bilelmoussaoui** [comment]
> Seems fine to me but needs some checking if it's guaranteed that all callers initialize the 4 values

Does it matter that much? because we have default values that corresponds to the C implementation ones unless I'm missing some case.  I have tried it with various widgets on a application I'm porting to gtk4 and it seems to works fine.

I will go ahead and merge this one, so that we can discover others :P

**Review by bilelmoussaoui — APPROVED** [review]

**Comment by sdroege** [comment]
> Does it matter that much?

If it's not guaranteed then we would initialize on our side with random values and that potentially breaks things in a hard to debug way.

**Comment by bilelmoussaoui** [comment]
From the examples of code i've found in gtk 's source tree, the only the two latest parameters that can expect a NULL as a value which defaults to -1. 
Per the docs a widget doesn't have to provide a measure function if it uses a layout manager but a layout manager doesn't care about the measure implementation at all so it shouldn't cause an issue from that side.

**Comment by sdroege** [comment]
> From the examples of code i've found in gtk 's source tree, only the two latest parameters that can expect a NULL as a value which defaults to -1.

Them being `NULL` is not so much a problem. A problem would be if they're not `NULL` but the caller does not initialize them to something meaningful (0/0/-1/-1).

>  Per the docs a widget doesn't have to provide a measure function if it uses a layout manager but a layout manager doesn't care about the measure implementation at all so it shouldn't cause an issue from that side.

`GtkWidget` implements that virtual method, so every widget will have some implementation of it. And (some?) layout managers seem to be calling the widget implementations of this function to figure out things.

**Comment by BrainBlasted** [comment]
I think those initial values are right, and then calling `imp.measure()` will mutate them according to the handling of the parent class if the user does not override `measure()`. I'm not sure where a problem comes in. This fixes the issue we had before with incorrect measure, I think.

**Comment by sdroege** [comment]
The issue would be if C code calls `klass->measure()` with pointers to uninitialized integers and assumes that the function initializes them without reading first. That does not seem to be the case in callers so it's probably fine here.

**Pull request merged**
