### PR TITLE
book: Take advantage of the newly introduced `builder` method

### PR DESCRIPTION
**Pull request by Hofer-Julian**
It was in introduced in PR #401

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Do you want doing the same thing for the examples as well?

**Comment by Hofer-Julian** [comment]
(Nearly) done!

Any idea though why `Application` has no builder method?
https://gtk-rs.org/gtk4-rs/git/docs/gtk4/struct.Application.html

**Comment by bilelmoussaoui** [comment]
> (Nearly) done!
> 
> Any idea though why `Application` has no builder method?
> https://gtk-rs.org/gtk4-rs/git/docs/gtk4/struct.Application.html

Please open an issue, I have an idea what can be the cause of that

**Comment by bilelmoussaoui** [comment]
No need to actually, because Application's code is manual that's why. I need to investigate why it's the case though

**Comment by Hofer-Julian** [comment]
> No need to actually, because Application's code is manual that's why. I need to investigate why it's the case though

Sure, I've opened https://github.com/gtk-rs/gtk4-rs/issues/405 for now.
Unless you have comments, I'd like to merge this PR then, so I can rebase the other book branch then.

**Pull request merged**
