### PR TITLE
0.9 backports

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
I would wait till we land the latest gir files before doing a release as it contains some annotations fixes

**Comment by sdroege** [comment]
Ok, then let's wait for that also for gtk-rs-core

**Comment by bilelmoussaoui** [comment]
https://github.com/gtk-rs/gtk4-rs/pull/1907 would need to be backported as well

**Comment by sdroege** [comment]
Done

**Pull request merged**
