### PR TITLE
Update gir (Gir.toml format update for gir directories)

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
From https://github.com/gtk-rs/gir/pull/1041.

I still wonder if we should keep the default value for `--gir-files-directory` in the `generator.py`...

### CODE REVIEW

**Comment by MarijnS95** [comment]
I guess this supersedes #212 in some way? That PR also separates out the files (which should be done separately for review anyway) and has review suggesting to use `-d` instead of `girs_directories` for less clutter.

**Comment by bilelmoussaoui** [comment]
Oups, i completely missed this one. Do you mind rebasing ?

**Comment by GuillaumeGomez** [comment]
I'll fully re-make it. It'll be simpler. ;)

**Comment by GuillaumeGomez** [comment]
Updated.

**Comment by bilelmoussaoui** [comment]
Thanks!

**Pull request merged**
