### PR TITLE
implement subclassing for scrolledwindow

### PR DESCRIPTION
**Pull request by vhdirk**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
I'm pretty sure it's a final type

**Comment by bilelmoussaoui** [comment]
Note that in gtk4, you're expected to subclass gtk::Widget and set whatever widget as it's child widget instead of subclassing everything

**Comment by sdroege** [comment]
> I'm pretty sure it's a final type

It is, there is no struct definition in the header.

**Comment by vhdirk** [comment]
Thanks, I've only just started porting to gtk4. Not having to subclass every possible widget seems much easier indeed.

**Comment by ids1024** [comment]
> It is, there is no struct definition in the header.

This also seems to be properly documented in the [generated API docs](https://docs.gtk.org/gtk4/class.ScrolledWindow.html) now (assuming that's always accurate): 

> ```vala
> final class Gtk.ScrolledWindow : Gtk.Widget {
>  /* No available fields */
> }
> ```

**Comment by sdroege** [comment]
I think that is only listed in the docs if the new GLib 2.70 `G_TYPE_FLAG_FINAL` is used.

**Pull request closed without merging**
