### PR TITLE
book: Extend main loop chapter with async section

### PR DESCRIPTION
**Pull request by Hofer-Julian**
See discussion in https://github.com/gtk-rs/gtk4-rs/pull/1508

- [x] Show how to await on `gio::spawn_blocking`
- [x] Await on ashpd
- [x] Use reqwest with tokio

### CODE REVIEW

**Comment by sdroege** [comment]
Let me know when you want me to go over it for a review :)

**Comment by Hofer-Julian** [comment]
> Let me know when you want me to go over it for a review :)

Thanks! Will do that :)

**Comment by Hofer-Julian** [comment]
@sdroege @felinira this PR is now ready for review. Feel free to also comment on parts of the chapter that wasn't touched by this PR.

You can render it locally by running:

```
cargo install mdbook
git switch Hofer-Julian/book-async
mdbook serve book
```

CI fails because I reference listings that will be there after this PR is merged.

**Review by Hofer-Julian — COMMENTED** [review]
Thanks for the review @felinira!
Your suggestions make sense to me and I applied most of the immediately :)

**Comment by sdroege** [comment]
A bit late, but I went through everything now and don't have a single suggestion what to change. Good work, this is a lot more understandable and short than what I would've come up with :)

**Pull request merged**
