### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by sdroege** [comment]
Hm that test failure is strange. It was passing fine here for me

**Comment by sdroege** [comment]
Can you reproduce the failure?

**Comment by bilelmoussaoui** [comment]
> Can you reproduce the failure?

it is probably caused by a gtk change

**Comment by sdroege** [comment]
Let's get this in then and handle the failure separately. It also happens otherwise in git currently.

**Pull request merged**
