### PR TITLE
[gtk] Default to trust_return_value_nullability

### PR DESCRIPTION
**Pull request by sophie-h**
Can we do it this way round? Here, every Object marked with `trust_return_value_nullability = false` should be checked and fixed at some point.

#68

### CODE REVIEW

**Comment by sdroege** [comment]
Makes it more obvious which ones still need to be taken care of, so I like it

**Comment by bilelmoussaoui** [comment]
Sounds good to me, but let's wait until the regen with 2018 edition in first.

**Comment by bilelmoussaoui** [comment]
The regen with 2018 edition is now, this can now be rebased. It seems that the bindings were not re-generated btw

**Comment by sophie-h** [comment]
The point of this PR is that nothing in the bindings changes at all. It's just a change in how we use `trust_return_value_nullability`.

**Comment by bilelmoussaoui** [comment]
Ah my bad. Didn't notice the global change of `trust_return_value_nullability`

**Pull request merged**
