### PR TITLE
book: remove `try_property`

### PR DESCRIPTION
**Pull request by Jedsek**

### CODE REVIEW

**Comment by Jedsek** [comment]
just a minor change, see [new release blog](https://gtk-rs.org/blog/2022/10/18/new-release.html#removing-result-wrapping-in-some-functions-returned-values)

**Comment by Hofer-Julian** [comment]
Thanks!

Feel free to just remove the whole sentence as well as the one before it.

**Comment by alatiera** [comment]
It's possible that you might have code that deals with objects that have different properties and needs to check if its present. While `try_property` is now gone you can still get an optional `some_object.property::<Option<T>>("property-name")`

**Comment by Hofer-Julian** [comment]
@alatiera Good point!

**Comment by Hofer-Julian** [comment]
Thanks!

**Pull request merged**
