### PR TITLE
Regenerate after updated gir-files update

### PR DESCRIPTION
**Pull request by MarijnS95**
gir-files for gtk4 have been updated in https://github.com/gtk-rs/gir-files/pull/74; regenerate and deal with a nullability change in `Gsk4.Transform::equal.

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
@sdroege this PR is problematic as the relevant gir-files changes were not merged yet iirc

**Comment by bilelmoussaoui** [comment]
or at least it points to a commit that doesn't exists in the master branch yet

**Comment by haecker-felix** [comment]
... which makes it currently impossible to use gtk4-rs in new projects.

```
    Updating git submodule `https://github.com/gtk-rs/gir-files.git`
error: failed to get `gtk4` as a dependency of package `fragments v0.1.0 (/home/haecker-felix/Dokumente/Projekte/Fragments)`

Caused by:
  failed to load source for dependency `gtk4`

Caused by:
  Unable to update https://github.com/gtk-rs/gtk4-rs

Caused by:
  failed to update submodule `gir-files`

Caused by:
  object not found - no match for id (f6c053d01a0c252b21e97739901f13760ced8193); class=Odb (9); code=NotFound (-3)
```

**Comment by MarijnS95** [comment]
@bilelmoussaoui I guess it's time to review, approve and merge https://github.com/gtk-rs/gir-files/pull/74 then :grimacing:

**Comment by sdroege** [comment]
Huh, why did it succeed the CI then?

**Comment by sdroege** [comment]
Can someone submit a new PR that fixes the commit id of the gir-files submodule? The gir-files PR is merged now (I thought I merged it already but apparently not...)

**Comment by bilelmoussaoui** [comment]
> Huh, why did it succeed the CI then?

I don't know? ^^

**Comment by MarijnS95** [comment]
https://github.com/gtk-rs/gtk4-rs/blob/96ab2717bf67ae9106d255f4f67ea5779d73a20d/.github/workflows/CI.yml#L109

This. Github clones the submodules and is "smart enough" to figure out that that commit hash lives in a fork, likely so that projects don't get CI errors until all dependencies are merged first.

However, @haecker-felix is using this project through cargo, which _cannot_ resolve to forks.

**Comment by MarijnS95** [comment]
@sdroege Sent.

**Comment by MarijnS95** [comment]
I don't think it matters "too much" now, https://github.com/gtk-rs/gir-files/commit/f6c053d is reachable from master now but it's cleaner to point to the merge commit I guess :grimacing:

**Pull request merged**
