### PR TITLE
 misc: drop unneeded Deref impls 

### LINKED ISSUE #806: Drop unwanted Deref impl for Events/RenderNodes/Expressions
see 
- https://github.com/gtk-rs/gtk4-rs/blob/master/gdk4/src/event.rs#L135-L141
- https://github.com/gtk-rs/gtk4-rs/blob/master/gtk4/src/expression.rs#L236-L242
- https://github.com/gtk-rs/gtk4-rs/blob/master/gsk4/src/render_node.rs#L114-L120

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
fixes #806

### CODE REVIEW

**Comment by sdroege** [comment]
These all seem like useful `Deref` impls: you can directly call into the (safe!) base class API.

**Comment by bilelmoussaoui** [comment]
Right, does glib::wrapper generates those for child -> parent cases?

**Comment by sdroege** [comment]
No because `GObject`s can have multiple parents (base class and interfaces), and that's why we have the `IsA` trait there.

**Comment by bilelmoussaoui** [comment]
Makes sense; will go ahead and close this one then

**Pull request closed without merging**
