### PR TITLE
subclassing: Remove measure vfunc from Widget subclassing

### PR DESCRIPTION
**Pull request by BrainBlasted**
This vfunc should be avoided, and the current handling breaks
widget subclassing. After talking with mclasen of the GTK
team, I believe removing it is the best course of actions.

Using layout managers is preferred over the measure vfunc.

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
imho layout managers have their own measure function as well, this needs discussion & hopefully a proper patch

**Comment by sdroege** [comment]
Lots of C widgets are using `measure`, so it's probably useful to have for special cases at least. Instead of removing it, the default behaviour should be fixed so that it behaves as if it was not overridden.

If that's not possible then this needs a fix on the C side.

**Comment by sdroege** [comment]
How exactly does it fail / cause problems currently?

**Comment by BrainBlasted** [comment]
It's a critcal failure and the app closes.

Screenshot from 2020-11-23 17-17-33

<details>
<summary>Backtrace</summary>

```
(gdb) bt
#0  0x00007ffff709b9d5 in raise () at /lib64/libc.so.6
#1  0x00007ffff70848a4 in abort () at /lib64/libc.so.6
#2  0x00007ffff728cb6c in g_assertion_message (domain=<optimized out>, file=0x7ffff7c60665 "../gtk/gtksizerequestcache.c", line=<optimized out>, func=<optimized out>, message=<optimized out>) at ../glib/gtestutils.c:2936
#3  0x00007ffff72e70ef in g_assertion_message_expr
    (domain=0x7ffff7c1205f "Gtk", file=0x7ffff7c60665 "../gtk/gtksizerequestcache.c", line=85, func=0x7ffff7c60f30 <__func__.0.lto_priv.218> "_gtk_size_request_cache_commit", expr=<optimized out>) at ../glib/gtestutils.c:2962
#4  0x00007ffff79c99e4 in _gtk_size_request_cache_commit
    (natural_baseline=<optimized out>, minimum_baseline=<optimized out>, natural_size=<optimized out>, minimum_size=318, for_size=-1, orientation=GTK_ORIENTATION_HORIZONTAL, cache=0x5555557be1d0) at ../gtk/gtksizerequestcache.c:85
#5  gtk_widget_query_size_for_orientation (widget=0x5555557be290, orientation=<optimized out>, for_size=-1, minimum=0x7fffffffd2f4, natural=0x7fffffffd2f0, minimum_baseline=0x0, natural_baseline=0x0) at ../gtk/gtksizerequest.c:402
#6  0x00007ffff79ca2ea in gtk_widget_get_preferred_size (widget=0x5555557be290, minimum_size=0x7fffffffd368, natural_size=0x0) at ../gtk/gtksizerequest.c:610
#7  0x00007ffff7a853ff in gtk_window_compute_hints (new_flags=<synthetic pointer>, new_geometry=<synthetic pointer>, window=0x5555557be290) at ../gtk/gtkwindow.c:5785
#8  gtk_window_compute_configure_request (window=window@entry=0x5555557be290, request=request@entry=0x7fffffffd420, geometry=geometry@entry=0x7fffffffd410, flags=flags@entry=0x7fffffffd3fc) at ../gtk/gtkwindow.c:5368
#9  0x00007ffff7a8596a in gtk_window_move_resize (window=0x5555557be290) at ../gtk/gtkwindow.c:5453
#10 gtk_window_native_check_resize (native=<optimized out>) at ../gtk/gtkwindow.c:1889
#11 gtk_window_native_check_resize (native=<optimized out>) at ../gtk/gtkwindow.c:1879
#12 0x00007ffff7a8523a in gtk_window_show (widget=0x5555557be290) at ../gtk/gtkwindow.c:3790
#13 0x0000555555566f0f in gtk4::subclass::widget::{{impl}}::parent_show<composite_template::ExApplicationWindowPriv> (self=0x5555557be020, widget=0x7fffffffd578) at /home/chris/Projects/gtk4-rs/gtk4/src/subclass/widget.rs:420
#14 0x00005555555668b3 in gtk4::subclass::widget::WidgetImpl::show<composite_template::ExApplicationWindowPriv> (self=0x5555557be020, widget=0x7fffffffd578) at /home/chris/Projects/gtk4-rs/gtk4/src/subclass/widget.rs:92
#15 0x0000555555560496 in gtk4::subclass::widget::widget_show<composite_template::ExApplicationWindowPriv> (ptr=0x5555557be290) at /home/chris/Projects/gtk4-rs/gtk4/src/subclass/widget.rs:749
#16 0x00007ffff73d1080 in _g_closure_invoke_va (param_types=0x0, n_params=<optimized out>, args=0x7fffffffd740, instance=0x5555557be290, return_value=0x0, closure=0x55555574fbc0) at ../gobject/gclosure.c:873
#17 g_signal_emit_valist (instance=0x5555557be290, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffd740) at ../gobject/gsignal.c:3403
#18 0x00007ffff73d11a3 in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../gobject/gsignal.c:3550
#19 0x00007ffff7a6f206 in gtk_widget_show (widget=0x5555557be290) at ../gtk/gtkwidget.c:2592
#20 0x0000555555566b4e in gtk4::auto::widget::{{impl}}::show<composite_template::ExApplicationWindow> (self=0x7fffffffd860) at /home/chris/Projects/gtk4-rs/gtk4/src/auto/widget.rs:1643
#21 0x00005555555688d0 in composite_template::main::{{closure}} (app=0x7fffffffd8b8) at examples/src/bin/composite_template.rs:102
#22 0x000055555556480c in gio::auto::application::{{impl}}::connect_activate::activate_trampoline<gtk4::auto::application::Application,closure-0> (this=0x7fffe400b720, f=0x1)
    at /home/chris/.cargo/git/checkouts/gtk-rs-48ef14c1f17c79fb/151db71/gio/src/auto/application.rs:556
#23 0x00007ffff73b3e2a in g_closure_invoke (closure=0x55555569b540, return_value=0x0, n_param_values=1, param_values=0x7fffffffda70, invocation_hint=0x7fffffffd9f0) at ../gobject/gclosure.c:810
#24 0x00007ffff73dd273 in signal_emit_unlocked_R.isra.0
    (node=node@entry=0x5555556a8e70, detail=detail@entry=0, instance=instance@entry=0x7fffe400b720, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffda70) at ../gobject/gsignal.c:3738
#25 0x00007ffff73d0f82 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffdc20) at ../gobject/gsignal.c:3494
#26 0x00007ffff73d11a3 in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../gobject/gsignal.c:3550
#27 0x00007ffff74d5a68 in g_application_real_local_command_line (application=0x7fffe400b720, arguments=0x7fffffffdd78, exit_status=0x7fffffffdd74) at ../gio/gapplication.c:1139
#28 0x00007ffff74d5c46 in g_application_run (application=0x7fffe400b720, argc=-8844, argv=<optimized out>) at ../gio/gapplication.c:2528
#29 0x0000555555561373 in gio::application::{{impl}}::run<gtk4::auto::application::Application> (self=0x7fffffffdeb0, argv=...) at /home/chris/.cargo/git/checkouts/gtk-rs-48ef14c1f17c79fb/151db71/gio/src/application.rs:20
#30 0x0000555555564f6f in composite_template::main () at examples/src/bin/composite_template.rs:105
```
</details>

**Comment by bilelmoussaoui** [comment]
@sdroege I think not calling the parent measure impl would solve it. Not sure if it's possible though?

**Comment by BrainBlasted** [comment]
Wouldn't that mean when override_vfuncs is called, it would set a measure() function that does nothing? I'm not sure that's what we want

**Comment by sdroege** [comment]
Can you provide a small testcase that reproduces the problem? I'm not entirely sure what happens there.

**Comment by BrainBlasted** [comment]
The example in the template MR reproduces it.

**Comment by sdroege** [comment]
This happens because our current code assumes that the parent impl will always set min/nat/min_base/nat_base. That's not the case.

I'm not entirely sure how this virtual method is actually supposed to work though. I believe the caller is supposed to initialize all 4 values (usually to 0/0/-1/-1) and then need to pass them through from the caller and they might then get adjusted along the way.

This means they either need to be `&mut i32` on the Rust side, or `(i32, i32, i32, i32) -> (i32, i32, i32, i32)`. For this case mutable references seem nicer though, but feel free to disagree.

Note that nonetheless you need to handle `NULL` being passed in, in which case 0/0/-1/-1 seems to be the standard initialization.

What I'm not entirely sure about is that "standard initialization" and whether all the callers actually always initialize those values.

Someone who cares about GTK needs to investigate this properly and map it to a Rust API.

**Comment by sdroege** [comment]
This is a potential fix but someone should double-check it.

```diff
diff --git a/gtk4/src/subclass/widget.rs b/gtk4/src/subclass/widget.rs
index e504f707..b6652a39 100644
--- a/gtk4/src/subclass/widget.rs
+++ b/gtk4/src/subclass/widget.rs
@@ -1,5 +1,3 @@
-use std::mem;
-
 use glib::prelude::*;
 use glib::subclass::prelude::*;
 use glib::translate::*;
@@ -53,8 +51,12 @@ pub trait WidgetImpl: WidgetImplExt + ObjectImpl {
         widget: &Self::Type,
         orientation: Orientation,
         for_size: i32,
-    ) -> (i32, i32, i32, i32) {
-        self.parent_measure(widget, orientation, for_size)
+        min: &mut i32,
+        nat: &mut i32,
+        min_base: &mut i32,
+        nat_base: &mut i32,
+    ) {
+        self.parent_measure(widget, orientation, for_size, min, nat, min_base, nat_base)
     }
 
     fn mnemonic_activate(&self, widget: &Self::Type, group_cycling: bool) -> bool {
@@ -141,7 +143,11 @@ pub trait WidgetImplExt: ObjectSubclass {
         widget: &Self::Type,
         orientation: Orientation,
         for_size: i32,
-    ) -> (i32, i32, i32, i32);
+        min: &mut i32,
+        nat: &mut i32,
+        min_base: &mut i32,
+        nat_base: &mut i32,
+    );
     fn parent_mnemonic_activate(&self, widget: &Self::Type, group_cycling: bool) -> bool;
     fn parent_move_focus(&self, widget: &Self::Type, direction_type: DirectionType);
     fn parent_query_tooltip(
@@ -293,7 +299,11 @@ impl<T: WidgetImpl> WidgetImplExt for T {
         widget: &Self::Type,
         orientation: Orientation,
         for_size: i32,
-    ) -> (i32, i32, i32, i32) {
+        min: &mut i32,
+        nat: &mut i32,
+        min_base: &mut i32,
+        nat_base: &mut i32,
+    ) {
         unsafe {
             let data = T::type_data();
             let parent_class = data.as_ref().get_parent_class() as *mut ffi::GtkWidgetClass;
@@ -302,27 +312,15 @@ impl<T: WidgetImpl> WidgetImplExt for T {
                 .measure
                 .expect("No parent class impl for \"measure\"");
 
-            let mut minimum_size = mem::MaybeUninit::uninit();
-            let mut natural_size = mem::MaybeUninit::uninit();
-            let mut minimum_base_size = mem::MaybeUninit::uninit();
-            let mut natural_base_size = mem::MaybeUninit::uninit();
-
             f(
                 widget.unsafe_cast_ref::<Widget>().to_glib_none().0,
                 orientation.to_glib(),
                 for_size,
-                minimum_size.as_mut_ptr(),
-                natural_size.as_mut_ptr(),
-                minimum_base_size.as_mut_ptr(),
-                natural_base_size.as_mut_ptr(),
+                min,
+                nat,
+                min_base,
+                nat_base,
             );
-
-            (
-                minimum_size.assume_init(),
-                natural_size.assume_init(),
-                minimum_base_size.assume_init(),
-                natural_base_size.assume_init(),
-            )
         }
     }
 
@@ -655,7 +653,33 @@ unsafe extern "C" fn widget_measure<T: WidgetImpl>(
     let wrap: Borrowed<Widget> = from_glib_borrow(ptr);
     let orientation = from_glib(orientation_ptr);
 
-    let (min, nat, min_base, nat_base) = imp.measure(wrap.unsafe_cast_ref(), orientation, for_size);
+    let mut min = 0;
+    let mut nat = 0;
+    let mut min_base = -1;
+    let mut nat_base = -1;
+    if !min_ptr.is_null() {
+        min = *min_ptr;
+    }
+    if !nat_ptr.is_null() {
+        nat = *nat_ptr;
+    }
+    if !min_base_ptr.is_null() {
+        min_base = *min_base_ptr;
+    }
+    if !nat_base_ptr.is_null() {
+        nat_base = *nat_base_ptr;
+    }
+
+    imp.measure(
+        wrap.unsafe_cast_ref(),
+        orientation,
+        for_size,
+        &mut min,
+        &mut nat,
+        &mut min_base,
+        &mut nat_base,
+    );
+
     if !min_ptr.is_null() {
         *min_ptr = min;
     }
```

**Comment by BrainBlasted** [comment]
Thanks - going to close this and re-submit with those changes

**Pull request closed without merging**
