### PR TITLE
gtk: use "assertion" = "skip" instead of manual implementation

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Review by bilelmoussaoui — APPROVED** [review]

**Comment by bilelmoussaoui** [comment]
Thanks!

**Review by sdroege — APPROVED** [review]

**Comment by bilelmoussaoui** [comment]
Same for this one as well it seems. Re-triggering the CI doesn't help somehow

**Comment by sdroege** [comment]
> Same for this one as well it seems. Re-triggering the CI doesn't help somehow

You have to rebase it on top of a version that includes the commit that fixes it.

**Comment by sdroege** [comment]
Rebased

**Pull request merged**
