### PR TITLE
file_chooser_native: Fix filters

### PR DESCRIPTION
**Pull request by A6GibKm**
Filters have to be manually added after creating the file chooser gobject as it has no "filter" gproperty. Following the about dialog
builder, the api is changed so that it can take multiple filters.

Fixes: https://github.com/gtk-rs/gtk4-rs/issues/151.

### CODE REVIEW

**Comment by A6GibKm** [comment]
The feels when you notice you are in a auto file....

**Comment by bilelmoussaoui** [comment]
The same thing has to be done to both FileChooserDialogBuilder & FileChooserWidgetBuilder. Do you think you can do those as well? :)

**Comment by sdroege** [comment]
Before we implement all builders manually, maybe there's something that can be improved in gir so that only the missing/wrong pieces can be implemented manually?

**Comment by A6GibKm** [comment]
> The same thing has to be done to both FileChooserDialogBuilder & FileChooserWidgetBuilder. Do you think you can do those as well? :)

Yeah of course, but ... 

> Before we implement all builders manually, maybe there's something that can be improved in gir so that only the missing/wrong pieces can be implemented manually?

I don't know how that works to be honest, note that in this case, I had to modify the struct and two methods (build & filter which was renamed to add_filter), maybe the others can still be generated.

**Comment by sdroege** [comment]
You could add a `manual_builder` or something and that would then expect a `struct FooBuilderManual` (that is `pub(crate)` only!). That would then be stored inside the autogenerated builder and provides it with additional fields, would have some kind of "add things to the properties array" function, and you would add another `impl FooBuilder` block in the manual code to add setter functions for the new fields.

**Comment by bilelmoussaoui** [comment]
> You could add a `manual_builder` or something and that would then expect a `struct FooBuilderManual` (that is `pub(crate)` only!). That would then be stored inside the autogenerated builder and provides it with additional fields, would have some kind of "add things to the properties array" function, and you would add another `impl FooBuilder` block in the manual code to add setter functions for the new fields.

That can work, but it would also need a way to omit some properties from being used by the Builder. The issue here is that FileChooser has a filter property along with filters property; it seems the first one is the problematic one as setting it to something just doesn't work. 

I wonder how many other cases where the Builder has to be manually written other than #143.

**Comment by sophie-h** [comment]
I think there is nothing wrong with the current behavior. See https://github.com/gtk-rs/gtk4-rs/issues/151#issuecomment-817380187 for details.

**Comment by bilelmoussaoui** [comment]
Closing, see #151.

**Pull request closed without merging**
