### PR TITLE
book: Add nix to linux installation guide

### PR DESCRIPTION
**Pull request by khrj**
Adds instructions to start a new shell with gtk4 and gcc using [Nix](https://nixos.org/guides/how-nix-works.html) with [nix-command](https://nixos.wiki/wiki/Nix_command) enabled

### CODE REVIEW

**Comment by Hofer-Julian** [comment]
Not sure if we should include experimental commands. Maybe use the current way of installing nix packages?

**Comment by khrj** [comment]
nix-command (and flakes) isn't really in beta, it's been around for quite some time now. At this point, there's just two different ways of using nix, via the old CLI, and via the new one. If you wish, I can add instructions for the old CLI too.

**Comment by Hofer-Julian** [comment]
As long as you have to activate a experimental flag for the new one I will only accept instructions for the old one.

**Comment by khrj** [comment]
@Hofer-Julian Hey, this slipped out of my mind - I just realised that libraries won't be available when installed using a shell, regardless of whether it uses the old or new syntax. The dependencies need to be added to a derivation - I've updated the instructions accordingly

**Review by Hofer-Julian — APPROVED** [review]
Thanks!

**Pull request merged**
