### PR TITLE
examples: Use autobins

### PR DESCRIPTION
**Pull request by sophie-h**
Or is there a reason to use `autobins = false`?

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Because some examples might have specific dependencies such as the #152; or is that can still be made to work with autobins?

**Comment by sophie-h** [comment]
> Because some examples might have specific dependencies

Just keep the explicit definitions for binaries that need additional settings. These things mix just fine.

**Comment by bilelmoussaoui** [comment]
Oh cool, I wasn't aware of that. Do you mind sending a PR to do the same thing for gtk-rs? :)

**Comment by sophie-h** [comment]
Yes, I will also backport run_future in the coming days

**Comment by bilelmoussaoui** [comment]
Thank you!

**Comment by sdroege** [comment]
> Yes, I will also backport run_future in the coming days (Edit: Yes=No, I don't mind, will do laughing)

That would be great, thanks :)

**Pull request merged**
