### PR TITLE
More doc alias

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Regen from gtk-rs/gir#1026

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Weird failure, no?

**Comment by GuillaumeGomez** [comment]
Oh, maybe it's my gir-files submodule which wasn't up-to-date! Checking quickly.

**Comment by GuillaumeGomez** [comment]
Yep, it was that.

**Comment by bilelmoussaoui** [comment]
Nice, thanks a lot!

**Pull request merged**
