### PR TITLE
Gir.toml: Add bool_return_is_error on activate_action_variant

### LINKED ISSUE #762: Return a `Result` on `WidgetExt::activate_action` instead of a `bool`.
According to [C API reference](https://docs.gtk.org/gtk4/method.Widget.activate_action.html), it would only return false if the action name doesn't exist. User might want it to panic, or be told by the compiler

### PR DESCRIPTION
**Pull request by SeaDve**
Fixes #762

Haven't locally tested it yet

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
You need to run the generator.py to regen with the new changes

**Comment by SeaDve** [comment]
It fails at 
```shell
=> Building gir...
   Compiling gdk4 v0.3.0 (/home/dave/Projects/gtk4-rs/gdk4)
error[E0046]: not all trait items implemented, missing: `instance_init`
   --> gdk4/src/subclass/paintable.rs:144:1
    |
144 | unsafe impl<T: PaintableImpl> IsImplementable<T> for Paintable {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `instance_init` in implementation
    |
    = help: implement the missing item: `fn instance_init(_: &mut InitializingObject<T>) { todo!() }`

For more information about this error, try `rustc --explain E0046`.
error: could not compile `gdk4` due to previous error
Error: Command '['cargo', 'build', '--release']' returned non-zero exit status 101.
```

**Comment by sdroege** [comment]
> not sure if I'm missing something

Only a `cargo update`

**Comment by SeaDve** [comment]
thanks

**Review by sdroege — APPROVED** [review]

**Pull request merged**
