### PR TITLE
use AsRef<RenderNode> instead of IsRenderNode

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Would it be an api break to backport this to 0.1?

### CODE REVIEW

**Comment by sdroege** [comment]
> Would it be an api break to backport this to 0.1?

Yes, but we should then probably also do the same for the 5-6 other cases of custom inheritance that we have here, in gtk3-rs and in cairo and glib.

**Comment by sdroege** [comment]
Can the traits be removed now or are they still useful?

**Comment by bilelmoussaoui** [comment]
> > Would it be an api break to backport this to 0.1?
> 
> Yes, but we should then probably also do the same for the 5-6 other cases of custom inheritance that we have here, in gtk3-rs and in cairo and glib.

At least in gtk4-rs, they are all handled properly now. I don't think I will have the time to fix others though.

**Comment by bilelmoussaoui** [comment]
> Can the traits be removed now or are they still useful?

They are still useful for downcast/upcast methods

**Comment by sdroege** [comment]
> At least in gtk4-rs, they are all handled properly now. I don't think I will have the time to fix others though.

No problem, can you create an issue though? :)

**Comment by bilelmoussaoui** [comment]
From a quick look:

- gtk3-rs has only a `gdk::FromEvent` trait, it's not used on the APIs at all except for downcast/is_a kind of methods. No actions needed it seems
- There's none in gtk-rs-core

**Comment by bilelmoussaoui** [comment]
For cairo though, there's a Deref implementation so it's more or less the same thing. Maybe we should use AsRef there as well?

**Comment by bilelmoussaoui** [comment]
I will go ahead and merge this one, no backport to 0.1 but I will do a 0.2 in a week or so

**Pull request merged**
