### PR TITLE
Use impl IntoIterator<Item = Expression> in ClosureExpression params

### PR DESCRIPTION
**Pull request by SeaDve**
I'm not sure if I did it correctly

### CODE REVIEW

**Review by sdroege — APPROVED** [review]

**Comment by SeaDve** [comment]
it seems to not accept slices (`&[Expressions]`) anymore, but only array and others

**Comment by sdroege** [comment]
Maybe `impl IntoIterator<Item = impl AsRef<Expression>>` then?

**Comment by SeaDve** [comment]
And clone it inside the function?

**Comment by sdroege** [comment]
It's refcounted so why not

**Pull request merged**
