### PR TITLE
gir: Update and regenerate with `impl Trait` instead of named types

### PR DESCRIPTION
**Pull request by MarijnS95**
https://github.com/gtk-rs/gir/pull/1153

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Thanks! I will take care of handling the manual part in a separate MR

**Comment by bilelmoussaoui** [comment]
The changes on this PR are not needed anymore as I regenreated few days ago. I'm going to go ahead and close this one

Thanks

**Comment by MarijnS95** [comment]
@bilelmoussaoui The linked PR was split in two pieces, the part that refactors `gir` and drops `where:` has been merged, the original https://github.com/gtk-rs/gir/pull/1153 is still up for debate (after the release) so this PR is still relevant for the diff (though I should probably rebase and force-push it).

Feel free to leave it closed for a while to decrease noise, but we should reopen it before a force-push (or GH detaches the PR from the branch).

**Comment by bilelmoussaoui** [comment]
Sure, let me know when you want to update it. At worst I can take care of doing the update once the gir changes are in as it would require a bunch of manual changes well

**Comment by MarijnS95** [comment]
@bilelmoussaoui Is it time to reopen this?

**Comment by sdroege** [comment]
Seems like a good plan to get this in now, yes :)

**Comment by MarijnS95** [comment]
@bilelmoussaoui The `gir` PR was merged, can you reopen this so that I can force-push?

**Review by sdroege — APPROVED** [review]

**Pull request merged**
