### PR TITLE
CI: use components for rustfmt/clippy

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Review by sdroege — APPROVED** [review]
Why is this not a problem for gtk-rs?

**Comment by bilelmoussaoui** [comment]
> Why is this not a problem for gtk-rs?

because @MarijnS95 already did that yesterday :-)

**Comment by MarijnS95** [comment]
I thought @bilelmoussaoui was on the GTK4 case :)

https://github.com/gtk-rs/gtk-rs/pull/485 for reference. @bilelmoussaoui You might at least use the same justification in your commit :)

**Comment by bilelmoussaoui** [comment]
> I thought @bilelmoussaoui was on the GTK4 case :)



> [gtk-rs/gtk-rs#485](https://github.com/gtk-rs/gtk-rs/pull/485) for reference. @bilelmoussaoui You might at least use the same justification in your commit :)

**Comment by MarijnS95** [comment]
> It just took me a bit of time :p

Hehe no hurry, I thought you were on the case after mentioning something like that but it could have just as well meant something along the lines of "sure, sounds nice, feel free to PR" :grimacing:. But it's all taken care of now :smile:

**Pull request merged**
